"""
MODELLING RADIATIVE TORQUE DISRUPTION OF DUST GRAINS
====================================================
This module provides functions to compute the disruption size and timescale of dust grains
induced by radiative torques (RATs). The RATs are generated by anisotropic radiation field
in the interstellar medium (ISM). The module also provides functions to compute the RAT
efficiency, RAT torque, and RAT frequency. The module also provides functions to compute the
critical rotational frequency for disruption, gas damping timescale, and IR damping factor.
The module also provides functions to plot the disruption size and timescale of dust grains
induced by RATs.

By: Curro Rodriguez (currodri@gmail.com)
"""
# Importing libraries
import numpy as np
import matplotlib.pyplot as plt

# Constants
from unyt import mh,kb
sec2Myr = 3.1536e13
    
def disruption_frequency(a,Smax,rho_dust):
    """Compute the critical rotational frequency for 
    disruption.

    Args:
        a (float): grain radius in [cm]
        Smax (float): grain tensile strength [erg/cm^3]
        rho_dust (float): grain material density [g/cm^3]

    Returns:
        float: _description_
    """    
    return 2. / a * np.sqrt(Smax / rho_dust)

def gas_damping(a,rho_dust,mu,chi):
    """Compute the gas damping timescale.

    Args:
        a (float): grain radius in [cm]
        rho_dust (float): grain material density [g/cm^3]
        mu (float): local mean molecular weight
        chi (float): collisional factor [K^0.5/cm^3]

    Returns:
        float: gas damping timescale in [s]
    """    
    
    I = 8. * np.pi * rho_dust * a ** 5. / 15.
    
    vth = np.sqrt(2. * kb.to('cm**2*g/s**2/K').d / (mu*mh.to('g').d))
    
    tau = 3. * I / (4. * np.sqrt(np.pi) * chi * mh.to('g').d * mu * vth * a**4)
    
    return tau

def IR_damping_factor(G0,chi,a):
    """Compute the IR damping factor FIR.

    Args:
        G0 (float): fraction local energy density in terms of the Habing band
        chi (float): collisional factor [K^0.5/cm^3]
        a (float): grain radius in [cm]

    Returns:
        float: IR damping factor
    """    

    FIR = 0.038 * 1e3 * np.sqrt(10) * (1e-5/a) * (1.17*G0)**(2./3.) / chi
    
    return FIR

def RAT_efficiency(a,wav):
    """Compute the RAT efficiency.

    Args:
        a (float): grain radius in [cm]
        wav (float): mean wavelength of ISRF [cm]

    Returns:
        float: RAT efficiency
    """    
    
    Q_max = 0.4
    
    if a <= wav / 2.7:
        Q = 8. * (wav / a)**(-3)
    else:
        Q = Q_max
    return Q

def RAT_torque(a,wav,gamma,G0):
    """Compute the RAT torque.

    Args:
        a (float): grain radius in [cm]
        wav (float): mean wavelength of ISRF [cm]
        gamma (float): radiation field anisotropy
        G0 (float): fraction local energy density in terms of the Habing band

    Returns:
        float: torque [erg]
    """    
    
    Q = RAT_efficiency(a,wav)
    u_MMPP83 = 8.64e-13 # [erg/cm^3]
    
    torque = np.pi * a**2. * gamma * (1.17 * G0) * u_MMPP83 * (wav / (2.*np.pi)) * Q

    return torque

def RAT_frequency(a,rho_dust,G0,mu,chi,wav,gamma):
    """Compute the RAT equilibrium rotational frequency

    Args:
        a (float): grain radius in [cm]
        rho_dust (float): grain material density [g/cm^3]
        G0 (float): fraction local energy density in terms of the Habing band
        mu (float): local mean molecular weight
        chi (float): collisional factor [K^0.5/cm^3]
        wav (float): mean wavelength of ISRF [cm]
        gamma (float): radiation field anisotropy

    Returns:
        float: RAT frequency [1/s]
    """    
    
    # 1. Compute the FIR
    FIR = IR_damping_factor(G0,chi,a)
    
    # 2. Compute the gas damping timescale
    tau_gas = gas_damping(a,rho_dust,mu,chi)
    
    # 3. Compute the RAT torque
    torque = RAT_torque(a,wav,gamma,G0)
    
    # 4. Finally compute the frequency
    I = 8. * np.pi * rho_dust * a ** 5. / 15.
    w_RAT = torque * tau_gas / I

    return w_RAT

def RAT_timescale(a,rho_dust,Smax,G0,wav,gamma):
    
    # 1. Compute the disruption frequency
    w_disr = disruption_frequency(a,Smax,rho_dust)
    
    # 2. Compute the moment of inertia
    I = 8. * np.pi * rho_dust * a ** 5. / 15.
    
    # 3. Compute the RAT torque
    torque = RAT_torque(a,wav,gamma,G0)
    
    t = I * w_disr / torque

    return t

def plot_disruption(G0min,G0max,chimin,chimax,wav,gamma,mu):
    
    import matplotlib.pyplot as plt
    from mpl_toolkits.axes_grid1.inset_locator import inset_axes
    import seaborn as sns
    sns.set_theme(style="white")
    plt.rcParams.update({
        "text.usetex": True,
        "font.family": "serif",
        "font.serif": "Computer Modern Roman",
    })
    
    # 1. Setup the range of values for the table
    G0 = np.logspace(np.log10(G0min),np.log10(G0max),100)
    chi = np.logspace(np.log10(chimin),np.log10(chimax),100)
    
    # 2. Setup the dust properties
    a_CLarge = 1e-5 # [cm]
    s_C = 2.2 # [g/cm^3]
    linestyles = ['solid','dashed','dashdot','dotted']
    Smax_C = np.array([1e5,1e6,1e7,1e8]) # [erg/cm^3]
    ratio_CLarge = np.zeros((len(G0),len(chi)))
    t_CLarge = np.zeros((len(G0),len(chi),len(Smax_C)))
    wdisr_CLarge = disruption_frequency(a_CLarge,Smax_C,s_C)
    a_SilLarge = 1e-5 # [cm]
    s_Sil = 3.3 # [g/cm^3]
    Smax_Sil = np.array([1e5,1e6,1e7,1e8]) # [erg/cm^3]
    ratio_SilLarge = np.zeros((len(G0),len(chi)))
    t_SilLarge = np.zeros((len(G0),len(chi),len(Smax_Sil)))
    wdisr_SilLarge = disruption_frequency(a_SilLarge,Smax_Sil,s_Sil)

    # 3. Compute the tables
    for i in range(0, len(G0)):
        for j in range(0, len(chi)):
            ratio_CLarge[i,j] = RAT_frequency(a_CLarge,s_C,G0[i],mu,chi[j],wav,gamma)
            for k in range(0, len(Smax_C)):
                if ratio_CLarge[i,j] > wdisr_CLarge[k]:
                    t_CLarge[i,j,k] = RAT_timescale(a_CLarge,s_C,Smax_C[k],G0[i],wav,gamma)
            ratio_SilLarge[i,j] = RAT_frequency(a_SilLarge,s_Sil,G0[i],mu,chi[j],wav,gamma)
            for k in range(0, len(Smax_Sil)):
                if ratio_SilLarge[i,j] > wdisr_SilLarge[k]:
                    t_SilLarge[i,j,k] = RAT_timescale(a_SilLarge,s_Sil,Smax_Sil[k],G0[i],wav,gamma)
    
    
    # 4. Setup figure
    fig, axes = plt.subplots(1, 2, figsize=(8,5), dpi=300, facecolor='w', edgecolor='k')
    axes[0].set_ylabel(r'$G_0$', fontsize=16)
    axes[0].set_xlabel(r'$n_{\rm H} \sqrt{T}$ [K$^{1/2}$ cm$^{-3}$]',fontsize=16)
    axes[1].set_xlabel(r'$n_{\rm H} \sqrt{T}$ [K$^{1/2}$ cm$^{-3}$]',fontsize=16)
    
    axes[0].set_yscale('log')
    axes[0].set_xscale('log')
    axes[0].tick_params(labelsize=14)
    axes[0].xaxis.set_ticks_position('both')
    axes[0].yaxis.set_ticks_position('both')
    axes[0].minorticks_on()
    axes[0].tick_params(which='both',axis="both",direction="out")
    

    axes[1].set_yscale('log')
    axes[1].set_xscale('log')
    axes[1].tick_params(labelsize=14)
    axes[1].xaxis.set_ticks_position('both')
    axes[1].yaxis.set_ticks_position('both')
    axes[1].minorticks_on()
    axes[1].tick_params(which='both',axis="both",direction="out")
    axes[1].yaxis.set_label_position("right")
    axes[1].yaxis.tick_right()
    
    
    for k in range(0, len(Smax_C)):
        pcm1 = axes[0].contour(chi,G0,np.log10(t_CLarge[:,:,k]/sec2Myr),[-3,-2,-1,0,1],cmap='Spectral',linestyles=linestyles[k])
        
        contour = axes[0].contour(chi,G0,np.log10(ratio_CLarge/wdisr_CLarge[k]), levels=[0], colors='k',linestyles=linestyles[k])
        if k == 0:
            axes[0].clabel(pcm1, inline=True, fontsize=12)
            axes[0].clabel(contour, inline=True, fontsize=14, fmt=r'$w_{\rm RAT}\geq w_{\rm disr}$')

    for k in range(0, len(Smax_Sil)):
        pcm2 = axes[1].contour(chi,G0,np.log10(t_SilLarge[:,:,k]/sec2Myr),[-3,-2,-1,0,1],cmap='Spectral',linestyles=linestyles[k])    
        contour = axes[1].contour(chi,G0,np.log10(ratio_SilLarge/wdisr_CLarge[k]), levels=[0], colors='k',linestyles=linestyles[k])
        if k == 0:
            axes[1].clabel(pcm2, inline=True, fontsize=12)
            axes[1].clabel(contour, inline=True, fontsize=14, fmt=r'$w_{\rm RAT}\geq w_{\rm disr}$')
    
    axes[0].legend(loc='best',fontsize=14,frameon=False)
    axes[1].legend(loc='best',fontsize=14,frameon=False)
    fig.subplots_adjust(top=0.97,bottom=0.13,left=0.1,right=0.94,hspace=0,wspace=0)
    fig.savefig('disruption_size_RATD.png',format='png',dpi=300)
    
def plot_disruption_timescale(G0min,G0max,chimin,chimax,wav,gamma,mu):
    
    import matplotlib.pyplot as plt
    from mpl_toolkits.axes_grid1.inset_locator import inset_axes
    import seaborn as sns
    sns.set_theme(style="white")
    plt.rcParams.update({
        "text.usetex": True,
        "font.family": "serif",
        "font.serif": "Computer Modern Roman",
    })
    
    # 1. Setup the range of values for the table
    G0 = np.logspace(np.log10(G0min),np.log10(G0max),100)
    chi = np.logspace(np.log10(chimin),np.log10(chimax),100)
    
    # 2. Setup the dust properties
    a_CLarge = 1e-5 # [cm]
    s_C = 2.2 # [g/cm^3]
    linestyles = ['solid','dashed','dashdot','dotted']
    Smax_C = 2e7 # [erg/cm^3]
    ratio_CLarge = np.zeros((len(G0),len(chi)))
    t_CLarge = np.full((len(G0),len(chi)),fill_value=0*sec2Myr)
    wdisr_CLarge = disruption_frequency(a_CLarge,Smax_C,s_C)
    a_SilLarge = 1e-5 # [cm]
    s_Sil = 3.3 # [g/cm^3]
    Smax_Sil = 1.5e8 # [erg/cm^3]
    ratio_SilLarge = np.zeros((len(G0),len(chi)))
    t_SilLarge = np.full((len(G0),len(chi)),fill_value=0*sec2Myr)
    wdisr_SilLarge = disruption_frequency(a_SilLarge,Smax_Sil,s_Sil)

    # 3. Compute the tables
    for i in range(0, len(G0)):
        for j in range(0, len(chi)):
            ratio_CLarge[i,j] = RAT_frequency(a_CLarge,s_C,G0[i],mu,chi[j],wav,gamma)
            if ratio_CLarge[i,j] > wdisr_CLarge:
                t_CLarge[i,j] = RAT_timescale(a_CLarge,s_C,Smax_C,G0[i],wav,gamma)
            ratio_SilLarge[i,j] = RAT_frequency(a_SilLarge,s_Sil,G0[i],mu,chi[j],wav,gamma)
            if ratio_SilLarge[i,j] > wdisr_SilLarge:
                t_SilLarge[i,j] = RAT_timescale(a_SilLarge,s_Sil,Smax_Sil,G0[i],wav,gamma)
    
    
    # 4. Setup figure
    fig, axes = plt.subplots(1, 2, figsize=(8,5), dpi=300, facecolor='w', edgecolor='k',sharey=True,sharex=True)
    axes[0].set_ylabel(r'$G_0$', fontsize=16)
    axes[0].set_xlabel(r'$n_{\rm H} \sqrt{T}$ [K$^{1/2}$ cm$^{-3}$]',fontsize=16)
    axes[1].set_xlabel(r'$n_{\rm H} \sqrt{T}$ [K$^{1/2}$ cm$^{-3}$]',fontsize=16)
    
    axes[0].set_yscale('log')
    axes[0].set_xscale('log')
    axes[0].tick_params(labelsize=14)
    axes[0].xaxis.set_ticks_position('both')
    axes[0].yaxis.set_ticks_position('both')
    axes[0].minorticks_on()
    axes[0].tick_params(which='both',axis="both",direction="out")
    axes[0].set_ylim([G0min,G0max])
    axes[0].set_xlim([chimin,chimax])
    

    # axes[1].setk_xscale('log')
    axes[1].tick_params(labelsize=14)
    axes[1].xaxis.set_ticks_position('both')
    axes[1].yaxis.set_ticks_position('both')
    axes[1].minorticks_on()
    axes[1].tick_params(which='both',axis="both",direction="out")
    axes[1].yaxis.set_label_position("right")
    axes[1].yaxis.tick_right()
    axes[1].set_ylim([G0min,G0max])
    axes[1].set_xlim([chimin,chimax])

    # Plot the t_CLarge array in the first panel and add a common colorbar at the top
    pcm1 = axes[0].pcolormesh(chi,G0,np.log10(t_CLarge[:,:] / sec2Myr), cmap='magma',
                          vmin=-5, vmax=2)
    pcm1 = axes[0].contour(chi,G0,np.log10(t_CLarge[:,:]/sec2Myr),[-4,-3,-2,-1,0,1],cmap='Spectral',linestyles='-',
                           extent=[chimin, chimax, G0min, G0max],
                            origin='lower')
    
    contour = axes[0].contour(chi,G0,ratio_CLarge/wdisr_CLarge, levels=[1], colors='k',linestyles='-')
    axes[0].clabel(pcm1, inline=True, fontsize=12)
    axes[0].clabel(contour, inline=True, fontsize=14, fmt=r'$w_{\rm RAT}\geq w_{\rm disr}$')

    
    pcm2 = axes[1].pcolormesh(chi,G0,np.log10(t_SilLarge / sec2Myr), cmap='magma',
                          vmin=-5, vmax=2) 
    cbar_ax = inset_axes(axes[1], width="50%", height="3%", loc='lower right', borderpad=3.5)
    cbar = fig.colorbar(pcm2, cax=cbar_ax, orientation='horizontal')
    cbar.set_label(r'$\log_{10}(t_{\rm disr} / \rm Myr)$', fontsize=12)
    pcm2 = axes[1].contour(chi,G0,np.log10(t_SilLarge[:,:]/sec2Myr),[-4,-3,-2,-1,0,1],cmap='Spectral',linestyles='-')   
    contour = axes[1].contour(chi,G0,np.log10(ratio_SilLarge/wdisr_SilLarge), levels=[0], colors='k',linestyles='-')
    axes[1].clabel(pcm2, inline=True, fontsize=12)
    axes[1].clabel(contour, inline=True, fontsize=14, fmt=r'$w_{\rm RAT}\geq w_{\rm disr}$')
    
    # Add points to both plots showing the locations of the CNM, WNM, the WIM, and the HII regions
    # in the G0-chi plane with their names next to them
    colors = ['purple','red', 'blue', 'green','orange']
    labels = ['CNM', 'WNM', 'WIM', 'HII','PDR']
    positions = [(30*np.sqrt(100), 1e0), (0.3*np.sqrt(6e3), 1e0),
                 (0.05*np.sqrt(8e3), 1e0), (1e2*np.sqrt(1e4), 1e3),
                 (1e4*np.sqrt(750),1e5)]
    
    for i, (x, y) in enumerate(positions):
        axes[0].scatter(x, y, color=colors[i], marker='o', s=50)
        axes[0].text(x, y * 1.1, labels[i], fontsize=12, ha='center', va='bottom', color=colors[i])
    
    for i, (x, y) in enumerate(positions):
        axes[1].scatter(x, y, color=colors[i], marker='o', s=50)
        axes[1].text(x, y * 1.1, labels[i], fontsize=12, ha='center', va='bottom', color=colors[i])
    
    
    
    fig.subplots_adjust(top=0.97,bottom=0.13,left=0.1,right=0.94,hspace=0,wspace=0)
    fig.savefig('disruption_timescale_RATD.png',format='png',dpi=300)